#include <stdlib.h>
#include <stdio.h>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
	find the sum of the even-valued terms.
*/

int test(int below) {
	int a = 1, b = 1, i = 0, c;
	int sum = 0;
	while (1) {
		if((sum + (a + b)) >= below)
			return sum;
		c = a + b;
		a = b;
		b = c;
		if(b % 2 == 0)
			sum += b;
	}
	
	return sum;
}

int main(int argc, char* argv[]) {
	int solution = test(4000000); // 1089154
	printf("the sum of the even-valued terms: %d\n", solution);
	return 0;
}